### ISSUE TITLE
Unable to run demo on aarch64

### ISSUE THREAD

**Issue by afeezaziz** [RGB-Tools/rgb-lib-python#2]
Hello, when I would like to try the demo `./services.sh build` to run this demo so I was not able to run this link: `./services.sh start`
<img width="848" alt="Screenshot 2023-10-07 at 4 25 18 PM" src="https://github.com/RGB-Tools/rgb-lib-python/assets/677026/6ccad88d-3ee0-4a8b-884e-828c1fc8b248">

**Comment by nicbus** [comment]
Hi, it looks like you're trying to run the demo on an aarch64 device.

The aarch64 architecture is not currently supported. Please use an x86_64 device and it should work as expected.

**Comment by nicbus** [comment]
PR #3, now in master, should fix this, can you try again and confirm, please?

**Comment by afeezaziz** [comment]
I am still unable to run the demo

![Uploading Screenshot 2023-11-19 at 2.49.09 PM.png…]()

**Comment by afeezaziz** [comment]
I am still unable to run demo.

<img width="1024" alt="Screenshot 2023-11-19 at 2 49 09 PM" src="https://github.com/RGB-Tools/rgb-lib-python/assets/677026/d988d6ad-f7d8-4b15-b574-b74d4b05bac3">

**Comment by nicbus** [comment]
Hi, it seems like the build is now succeeding for you, but the resulting rgb-lib library is not working as expected.

As already said, though, the aarch64 architecture is not currently supported and we cannot debug this ourselves, sorry.

**Comment by afeezaziz** [comment]
Ok, not an issue then. I'll try on Ubuntu. 

So the issue remains, for _aarch64_ still unable to build.

**Comment by afeezaziz** [comment]
Bumping up this topic. Is it still not possible to run this demo on ARM64 or Macbook Apple Silicon?

**Comment by zoedberg** [comment]
We recently fixed rgb-lib-python to make it work on more platforms and architectures (see https://github.com/RGB-Tools/rgb-lib-python/commit/307eddbc0a915353d48458585a168c362c232e67), therefore the demo should work now. Could you please check and close the issue if it works? Thanks.

**Comment by afeezaziz** [comment]
Happy to say that the demo works! Thanks @zoedberg !
